# Generated by Django 5.2.14 on 2026-05-30 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_commandmessage_rich"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-featured_order", "-created_at"],
                "permissions": [
                    ("post_project", "Can post projects"),
                    ("edit_project", "Can edit projects"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="subcategory",
            field=models.ForeignKey(
                limit_choices_to={"parent__isnull": False},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="portfolio.projectcategory",
            ),
        ),
        migrations.AlterField(
            model_name="projectcommand",
            name="idea_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectcommand",
            name="objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectcommand",
            name="price_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcommand",
            name="problems",
            field=models.TextField(blank=True),
        ),
    ]
