# Generated by Django 5.2.14 on 2026-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_project_options_alter_comment_author_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcommand",
            name="tracking_code",
            field=models.CharField(
                db_index=True, editable=False, max_length=12, unique=True
            ),
        ),
    ]
