# Generated by Django 5.2.14 on 2026-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_store_product_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcommand",
            name="quoted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bill amount in USD when accepted (Stripe)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subscriptionpack",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="USD price for Stripe (international)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpack",
            name="price_dzd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="DZD price for Chargily (Algeria)",
                max_digits=12,
            ),
        ),
    ]
