# Generated by Django 5.1.15 on 2026-06-05 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_granular_staff_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("action", models.CharField(max_length=32)),
                ("resource", models.CharField(max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("object_label", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="commandlayer",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="storeorder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="storeproduct",
            options={"ordering": ["-is_featured", "sort_order", "name"]},
        ),
        migrations.RenameIndex(
            model_name="storestockreservation",
            new_name="portfolio_s_reserva_7213ec_idx",
            old_name="portfolio_st_reserv_6e2a0d_idx",
        ),
        migrations.AlterField(
            model_name="commandlayerbundle",
            name="layer_ids",
            field=models.JSONField(
                default=list,
                help_text="List of CommandLayer UUID strings included in this preset.",
            ),
        ),
        migrations.AddField(
            model_name="staffauditlog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="staffauditlog",
            index=models.Index(
                fields=["-created_at", "actor"], name="portfolio_s_created_58e224_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffauditlog",
            index=models.Index(
                fields=["resource", "-created_at"],
                name="portfolio_s_resourc_a9faa5_idx",
            ),
        ),
    ]
