# Generated by Django 5.1.15 on 2026-06-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0031_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcommand",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount actually charged",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectcommand",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectcommand",
            name="paid_currency",
            field=models.CharField(
                blank=True,
                help_text="usd or dzd — set when payment completes",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paid_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
